version: '3.6'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        volumes:
            - ./:/opt/app
        ports:
            - 8000:8000
        environment:
            DATABASE_URL: "postgres://postgres:postgres@db:5432/ITS"
        depends_on:
            - db
    db:
        image: postgres:10.0-alpine
        restart: always
        volumes:
            - ./data/postgres/pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: ITS
            PGDATA: '/var/lib/postgresql/data'
        ports:
            - 5432:5432