# Generated by Django 2.1.4 on 2019-01-11 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='date_start',
            new_name='date',
        ),
    ]
